CREATE TABLE USUARIO(
    USUARIO_ID      INTEGER NOT NULL AUTO_INCREMENT,
    NOME            VARCHAR(128) NOT NULL,
    SENHA           VARCHAR(64) NOT NULL,
    NOMEUSUARIO     VARCHAR(64) NOT NULL,
    TIPO            INTEGER NOT NULL,

    PRIMARY KEY (USUARIO_ID)
);

CREATE TABLE REGISTRO(
    REGISTRO_ID     INTEGER NOT NULL AUTO_INCREMENT,
    TIPO            VARCHAR(64) NOT NULL,
    ASSUNTO         VARCHAR(256) NOT NULL,
    NUMERO          VARCHAR(16) NOT NULL,
    DATA_           VARCHAR(16) NOT NULL,
    URL_            VARCHAR(128) NOT NULL,
    RESUMO          VARCHAR(512) NOT NULL,
    OBJETO          VARCHAR(128) NOT NULL,
    RECURSO         VARCHAR(64) NOT NULL,
    CONSIDERACAO    VARCHAR(128) NOT NULL,
    RECEPTOR        VARCHAR(64) NOT NULL,

    PRIMARY KEY (REGISTRO_ID)
);

CREATE TABLE SUPERINTENDENCIA(
    SUP_ID          INTEGER NOT NULL AUTO_INCREMENT,
    REGISTRO_ID     INTEGER NOT NULL,
    NOME            VARCHAR(64) NOT NULL,

    PRIMARY KEY (SUP_ID),
    FOREIGN KEY (REGISTRO_ID) REFERENCES REGISTRO (REGISTRO_ID)

);

CREATE TABLE ACOMPANHAMENTO(
    ACOMP_ID        INTEGER NOT NULL AUTO_INCREMENT,
    REGISTRO_ID     INTEGER NOT NULL,
    DATA_           DATE NOT NULL,
    STATUS_         VARCHAR(32) NOT NULL,
    OBS             VARCHAR(128) NOT NULL,

    PRIMARY KEY (ACOMP_ID),
    FOREIGN KEY (REGISTRO_ID) REFERENCES REGISTRO (REGISTRO_ID)
)

